
replicaCount: 1
namespace: 6bd63eb7-ef40-432f-992a-5eedc8670a0a
service: s-6bd63eb7-ef40-432f-992a-5eedc8670a0a
name: miha-e2dc3fd17429
host: e2dc3fd17429.miha-clound.com
image:
    repository: mihacloud/e2dc3fd17429
    tag: latest

keda:
    namespace: keda

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
    type: ClusterIP
    port: 80
    targetPort: 80
    annotations: {}

ingress:
    enabled: true
    className: "nginx"
    annotations: 
        kubernetes.io/ingress.class: "nginx"
    hosts:
        - host: e2dc3fd17429.miha-clound.com
          paths: 
            - path: /
              pathType: ImplementationSpecific
    tls: []

resources: 
    limits:
        cpu: 0.5
        memory: 512Mi
    
    requests:
        cpu: 0.1
        memory: 128Mi

autoscaling:
    enabled: true
    min: 0
    max: 1
    targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
                        